apiVersion: v1
kind: Template
metadata:
  name: launchpad-builder
  annotations:
    description: This template creates a Build Configuration using an S2I builder.
    tags: instant-app
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  required: true
- name: SOURCE_REPOSITORY_REF
  description: The branch name for the application
  displayName: Source Branch
  value: master
  required: true
- name: SOURCE_REPOSITORY_DIR
  description: The location within the source repo of the application
  displayName: Source Directory
  value: .
  required: true
- name: ARTIFACT_COPY_ARGS
  description: Syntax to be used to copy uberjar files to the target directory
  displayName: Copy Args
  value: '*-exec.jar'
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
- name: MAVEN_MIRROR_URL
  description: Maven Nexus Repository to be used during build phase
  displayName:
  required: false
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: spring-boot-hibernate-search
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: runtime
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: spring-boot-hibernate-search
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: spring-boot-hibernate-search:14
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      #contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: runtime:latest
        incremental: true
        env:
        - name: MAVEN_ARGS_APPEND
          value: "-pl ${SOURCE_REPOSITORY_DIR}"
        - name: ARTIFACT_DIR
          value: "${SOURCE_REPOSITORY_DIR}/target"
        - name: MAVEN_MIRROR_URL
          value: "${MAVEN_MIRROR_URL}"
        - name: ARTIFACT_COPY_ARGS
          value: "${ARTIFACT_COPY_ARGS}"
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: spring-boot-hibernate-search
      provider: fabric8
      version: "1"
      version: "1"
      group: dev.snowdrop.example
    name: my-database-secret
  stringData:
    user: luke
    password: secret
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/scm-con-url: scm:git:https://github.com/openshiftio/booster-parent.git/spring-boot-hibernate-search
      prometheus.io/port: "9779"
      fabric8.io/scm-url: https://github.com/openshiftio/spring-boot-hibernate-search
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/git-branch: sb-1.5.x
      prometheus.io/scrape: "true"
      fabric8.io/scm-devcon-url: scm:git:git:@github.com:openshiftio/booster-parent.git/spring-boot-hibernate-search
      fabric8.io/scm-tag: booster-parent-11
    labels:
      expose: "true"
      app: spring-boot-hibernate-search
      provider: fabric8
      version: "1"
      group: dev.snowdrop.example
    name: spring-boot-hibernate-search
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: spring-boot-hibernate-search
      provider: fabric8
      group: dev.snowdrop.example
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=spring-boot-hibernate-search&var-version=1
      fabric8.io/scm-con-url: scm:git:https://github.com/openshiftio/booster-parent.git/spring-boot-hibernate-search
      fabric8.io/scm-url: https://github.com/openshiftio/spring-boot-hibernate-search
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/git-branch: sb-1.5.x
      fabric8.io/scm-devcon-url: scm:git:git:@github.com:openshiftio/booster-parent.git/spring-boot-hibernate-search
      fabric8.io/scm-tag: booster-parent-11
    labels:
      app: spring-boot-hibernate-search
      provider: fabric8
      version: "1"
      group: dev.snowdrop.example
    name: spring-boot-hibernate-search
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: spring-boot-hibernate-search
      provider: fabric8
      group: dev.snowdrop.example
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=spring-boot-hibernate-search&var-version=1
          fabric8.io/scm-con-url: scm:git:https://github.com/openshiftio/booster-parent.git/spring-boot-hibernate-search
          fabric8.io/scm-url: https://github.com/openshiftio/spring-boot-hibernate-search
          fabric8.io/iconUrl: img/icons/spring-boot.svg
          fabric8.io/git-branch: sb-1.5.x
          fabric8.io/scm-devcon-url: scm:git:git:@github.com:openshiftio/booster-parent.git/spring-boot-hibernate-search
          fabric8.io/scm-tag: booster-parent-11
        labels:
          app: spring-boot-hibernate-search
          provider: fabric8
          version: "1"
          group: dev.snowdrop.example
      spec:
        containers:
        - env:
          - name: JAVA_OPTIONS
            value: -Dspring.profiles.active=openshift
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: spring-boot-hibernate-search:1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot
        from:
          kind: ImageStreamTag
          name: spring-boot-hibernate-search:1
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: spring-boot-hibernate-search
      provider: fabric8
      version: "1"
      group: dev.snowdrop.example
    name: spring-boot-hibernate-search
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: spring-boot-hibernate-search
